import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Main from '@/sections/home/main'
import Feature from '@/sections/home/feature'
import Testinomials from '@/sections/home/testinomials'
import { Cta } from '@/sections/home/cta'
import Footer from '@/components/footer'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='overflow-x-hidden ' >
      <Main/>
      <Feature/>
      <Testinomials/>
      <Cta/>
      <Footer/>
      </main>
    </>
  )
}
